import type { Database } from 'sql.js';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import type { AppPaths } from '../main/paths.js';
const electronRequire = createRequire(__filename);
const initSqlJs = electronRequire('sql.js') as typeof import('sql.js');
export class Persistence {
  private constructor(readonly db: Database, private readonly filename: string) { this.migrate(); }
  static async open(paths: AppPaths) { fs.mkdirSync(paths.data, { recursive: true, mode: 0o700 }); const SQL = await initSqlJs({ locateFile: (file) => electronRequire.resolve(`sql.js/dist/${file}`) }); const filename = `${paths.data}/classicmp.db`; const db = fs.existsSync(filename) ? new SQL.Database(fs.readFileSync(filename)) : new SQL.Database(); return new Persistence(db, filename); }
  private migrate() { this.db.run(`CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS media_history(id TEXT PRIMARY KEY, canonical_path TEXT, source_url TEXT, display_name TEXT NOT NULL, media_identity TEXT, duration_seconds REAL, last_position_seconds REAL, last_played_at TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0); CREATE INDEX IF NOT EXISTS history_last_played ON media_history(last_played_at); CREATE TABLE IF NOT EXISTS favorites(id TEXT PRIMARY KEY, name TEXT NOT NULL, source_type TEXT NOT NULL, source TEXT NOT NULL, position_seconds REAL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS saved_playlists(id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS saved_playlist_items(id TEXT PRIMARY KEY, playlist_id TEXT NOT NULL REFERENCES saved_playlists(id) ON DELETE CASCADE, position INTEGER NOT NULL, source_type TEXT NOT NULL, source TEXT NOT NULL, title TEXT);`); this.flush(); }
  getSettings(): Record<string, unknown> { const rows = this.db.exec('SELECT key,value_json FROM settings')[0]?.values ?? []; return Object.fromEntries(rows.map((r) => [String(r[0]), JSON.parse(String(r[1])) as unknown])); }
  setSettings(values: Record<string, unknown>) { Object.entries(values).forEach(([key, value]) => this.db.run('INSERT INTO settings(key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at', [key, JSON.stringify(value), new Date().toISOString()])); this.flush(); }
  resetSettings() { this.db.run('DELETE FROM settings'); this.flush(); }
  saveHistory(item: { id: string; path?: string | undefined; url?: string | undefined; displayName: string; identity: string; duration: number; position: number; completed: boolean }) { this.db.run('INSERT INTO media_history(id,canonical_path,source_url,display_name,media_identity,duration_seconds,last_position_seconds,last_played_at,completed) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET canonical_path=excluded.canonical_path,source_url=excluded.source_url,display_name=excluded.display_name,media_identity=excluded.media_identity,duration_seconds=excluded.duration_seconds,last_position_seconds=excluded.last_position_seconds,last_played_at=excluded.last_played_at,completed=excluded.completed', [item.id, item.path ?? null, item.url ?? null, item.displayName, item.identity, item.duration, item.position, new Date().toISOString(), item.completed ? 1 : 0]); this.flush(); }
  history(limit = 100) { const result = this.db.exec('SELECT id,canonical_path,source_url,display_name,media_identity,duration_seconds,last_position_seconds,last_played_at,completed FROM media_history ORDER BY last_played_at DESC LIMIT $limit', { '$limit': limit }); return result[0]?.values ?? []; }
  getResume(id: string) { const result = this.db.exec('SELECT id,display_name,duration_seconds,last_position_seconds,last_played_at,completed FROM media_history WHERE id=$id', { '$id': id }); return result[0]?.values[0] ?? null; }
  deleteHistory(id?: string) { if (id) this.db.run('DELETE FROM media_history WHERE id=$id', { '$id': id }); else this.db.run('DELETE FROM media_history'); this.flush(); }
  listFavorites() { return this.db.exec('SELECT id,name,source_type,source,position_seconds,created_at,updated_at FROM favorites ORDER BY name')[0]?.values ?? []; }
  saveFavorite(item: { id: string; name: string; sourceType: string; source: string; position?: number | undefined }) { const now = new Date().toISOString(); this.db.run('INSERT INTO favorites(id,name,source_type,source,position_seconds,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,source_type=excluded.source_type,source=excluded.source,position_seconds=excluded.position_seconds,updated_at=excluded.updated_at', [item.id, item.name, item.sourceType, item.source, item.position ?? null, now, now]); this.flush(); }
  deleteFavorite(id: string) { this.db.run('DELETE FROM favorites WHERE id=$id', { '$id': id }); this.flush(); }
  listPlaylists() { return this.db.exec('SELECT id,name,created_at,updated_at FROM saved_playlists ORDER BY name')[0]?.values ?? []; }
  savePlaylist(id: string, name: string, items: { id: string; sourceType: string; source: string; title?: string | undefined }[]) { const now = new Date().toISOString(); this.db.run('INSERT INTO saved_playlists(id,name,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,updated_at=excluded.updated_at', [id, name, now, now]); this.db.run('DELETE FROM saved_playlist_items WHERE playlist_id=$id', { '$id': id }); items.forEach((item, position) => this.db.run('INSERT INTO saved_playlist_items(id,playlist_id,position,source_type,source,title) VALUES(?,?,?,?,?,?)', [item.id, id, position, item.sourceType, item.source, item.title ?? null])); this.flush(); }
  getPlaylist(id: string) { const result = this.db.exec('SELECT id,name,created_at,updated_at FROM saved_playlists WHERE id=$id', { '$id': id }); const row = result[0]?.values[0]; if (!row) return null; const items = this.db.exec('SELECT id,source_type,source,title FROM saved_playlist_items WHERE playlist_id=$id ORDER BY position', { '$id': id })[0]?.values ?? []; return { id: row[0], name: row[1], createdAt: row[2], updatedAt: row[3], items }; }
  deletePlaylist(id: string) { this.db.run('DELETE FROM saved_playlists WHERE id=$id', { '$id': id }); this.flush(); }
  private flush() { fs.writeFileSync(this.filename, Buffer.from(this.db.export())); }
  close() { this.flush(); this.db.close(); }
}
