import Fastify, { type FastifyInstance } from 'fastify';
import { basename } from 'node:path';
import { randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { openSchema, seekSchema, speedSchema, volumeSchema, settingsSchema, historySchema, favoriteSchema, playlistSchema, trackSchema, externalMediaSchema, delaySchema } from '../shared/schemas.js';
import type { MpvAdapter } from '../playback/mpv/MpvAdapter.js';
import type { Persistence } from '../persistence/database.js';
export interface ApiContext { mpv: MpvAdapter; persistence: Persistence; version: string; screenshotDirectory: string; }
export async function createApi(ctx: ApiContext) { const token = randomBytes(32).toString('hex'); const app = Fastify({ logger: false, genReqId: () => randomUUID() });
  app.addHook('onRequest', async (req, reply) => { if (req.url === '/api/v1/events') return; const value = req.headers.authorization?.replace(/^Bearer\s+/, ''); if (!value || value.length !== token.length || !timingSafeEqual(Buffer.from(value), Buffer.from(token))) return reply.code(401).send({ error: { code: 'UNAUTHORIZED', message: 'Invalid local application session.', details: {}, requestId: req.id } }); });
  const fail = (reply: { code: (n: number) => { send: (x: unknown) => unknown } }, requestId: string, code: string, message: string) => reply.code(400).send({ error: { code, message, details: {}, requestId } });
  app.get('/api/v1/app/status', async () => ({ status: 'ok', version: ctx.version, apiVersion: 'v1', playbackEngine: { status: ctx.mpv.getState().status }, database: { status: 'ready' } }));
  app.get('/api/v1/app/version', async () => ({ version: ctx.version, apiVersion: 'v1' }));
  app.get('/api/v1/playback', async () => ctx.mpv.getState());
  app.post('/api/v1/playback/open', async (req, reply) => { const parsed = openSchema.safeParse(req.body); if (!parsed.success) return fail(reply, req.id, 'INVALID_REQUEST', parsed.error.issues[0]?.message || 'Invalid request'); const source = parsed.data.source.type === 'file' ? parsed.data.source.path : parsed.data.source.url; if (!source) return fail(reply, req.id, 'INVALID_REQUEST', 'Missing media source'); if (parsed.data.source.type === 'url' && !/^https?:\/\//i.test(source)) return fail(reply, req.id, 'INVALID_URL', 'Only HTTP and HTTPS URLs are supported'); ctx.mpv.open(source); return ctx.mpv.getState(); });
  const action = (name: 'play'|'pause'|'stop'|'toggle') => app.post(`/api/v1/playback/${name}`, async () => { if (name === 'play') ctx.mpv.play(); else if (name === 'pause') ctx.mpv.pause(); else if (name === 'stop') ctx.mpv.stop(); else ctx.mpv.getState().pause ? ctx.mpv.play() : ctx.mpv.pause(); return ctx.mpv.getState(); }); ['play','pause','stop','toggle'].forEach((n) => action(n as 'play'|'pause'|'stop'|'toggle'));
  app.post('/api/v1/playback/seek', async (req, reply) => { const p = seekSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid seek request'); ctx.mpv.seek(p.data.seconds, p.data.relative); return ctx.mpv.getState(); });
  app.post('/api/v1/playback/frame-step', async () => { ctx.mpv.frameStep(); return ctx.mpv.getState(); });
  app.post('/api/v1/playback/frame-back-step', async () => { ctx.mpv.frameStep(true); return ctx.mpv.getState(); });
  app.put('/api/v1/playback/speed', async (req, reply) => { const p = speedSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Speed must be between 0.25 and 4'); ctx.mpv.setSpeed(p.data.speed); return ctx.mpv.getState(); });
  app.put('/api/v1/playback/volume', async (req, reply) => { const p = volumeSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Volume must be between 0 and 130'); ctx.mpv.setVolume(p.data.volume); return ctx.mpv.getState(); });
  app.post('/api/v1/playback/mute', async () => { ctx.mpv.toggleMute(); return ctx.mpv.getState(); });
  app.post('/api/v1/video/screenshot', async () => ({ filename: ctx.mpv.screenshot(ctx.screenshotDirectory) }));
  app.get('/api/v1/playback/tracks', async () => ({ tracks: ctx.mpv.getMediaProperties().tracks }));
  const selectTrack = (kind: 'aid' | 'vid' | 'sid', key: 'audio' | 'video' | 'subtitle') => app.put(`/api/v1/playback/tracks/${key}`, async (req, reply) => { const p = trackSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid track id'); ctx.mpv.selectTrack(kind, p.data.id); return { ok: true, selected: p.data.id }; });
  selectTrack('aid', 'audio'); selectTrack('vid', 'video'); selectTrack('sid', 'subtitle');
  app.post('/api/v1/playback/subtitles/load', async (req, reply) => { const p = externalMediaSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid subtitle path'); ctx.mpv.loadSubtitle(p.data.path); return { ok: true }; });
  app.post('/api/v1/playback/audio/load', async (req, reply) => { const p = externalMediaSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid audio path'); ctx.mpv.loadAudio(p.data.path); return { ok: true }; });
  app.put('/api/v1/audio/delay', async (req, reply) => { const p = delaySchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid audio delay'); ctx.mpv.setDelay('audio-delay', p.data.seconds); return { seconds: p.data.seconds }; });
  app.put('/api/v1/subtitles/delay', async (req, reply) => { const p = delaySchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid subtitle delay'); ctx.mpv.setDelay('sub-delay', p.data.seconds); return { seconds: p.data.seconds }; });
  app.get('/api/v1/media/current', async () => ctx.mpv.getState());
  app.get('/api/v1/media/properties', async () => ({ playback: ctx.mpv.getState(), ...ctx.mpv.getMediaProperties() }));
  app.post('/api/v1/settings/reset', async () => { ctx.persistence.resetSettings(); return { ok: true }; });
  app.get('/api/v1/settings', async () => ctx.persistence.getSettings());
  app.put('/api/v1/settings/:section', async (req, reply) => { const p = settingsSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Settings must be an object'); ctx.persistence.setSettings({ [String((req.params as { section: string }).section)]: p.data }); return p.data; });
  app.get('/api/v1/history', async () => ctx.persistence.history().map((r) => ({ id: r[0], path: r[1], url: r[2], displayName: r[3], identity: r[4], duration: r[5], position: r[6], lastPlayedAt: r[7], completed: Boolean(r[8]) })));
  app.post('/api/v1/history', async (req, reply) => { const p = historySchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid history item'); ctx.persistence.saveHistory(p.data); return { ok: true }; });
  app.delete('/api/v1/history', async () => { ctx.persistence.deleteHistory(); return { ok: true }; });
  app.delete('/api/v1/history/:id', async (req) => { ctx.persistence.deleteHistory(String((req.params as { id: string }).id)); return { ok: true }; });
  app.get('/api/v1/resume/:mediaId', async (req) => { const r = ctx.persistence.getResume(String((req.params as { mediaId: string }).mediaId)); return r ? { id: r[0], displayName: r[1], duration: r[2], position: r[3], lastPlayedAt: r[4], completed: Boolean(r[5]) } : null; });
  app.delete('/api/v1/resume/:mediaId', async (req) => { ctx.persistence.deleteHistory(String((req.params as { mediaId: string }).mediaId)); return { ok: true }; });
  app.get('/api/v1/favorites', async () => ctx.persistence.listFavorites().map((r) => ({ id: r[0], name: r[1], sourceType: r[2], source: r[3], position: r[4], createdAt: r[5], updatedAt: r[6] })));
  app.post('/api/v1/favorites', async (req, reply) => { const p = favoriteSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid favorite'); ctx.persistence.saveFavorite(p.data); return p.data; });
  app.put('/api/v1/favorites/:id', async (req, reply) => { const p = favoriteSchema.safeParse({ ...(req.body as object), id: String((req.params as { id: string }).id) }); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid favorite'); ctx.persistence.saveFavorite(p.data); return p.data; });
  app.delete('/api/v1/favorites/:id', async (req) => { ctx.persistence.deleteFavorite(String((req.params as { id: string }).id)); return { ok: true }; });
  const listPlaylists = async () => ctx.persistence.listPlaylists().map((r) => ({ id: r[0], name: r[1], createdAt: r[2], updatedAt: r[3] }));
  app.get('/api/v1/playlists', listPlaylists);
  app.get('/api/v1/playlist', listPlaylists);
  app.get('/api/v1/playlist/:id', async (req, reply) => { const playlist = ctx.persistence.getPlaylist(String((req.params as { id: string }).id)); if (!playlist) return reply.code(404).send({ error: { code: 'NOT_FOUND', message: 'Playlist not found.', details: {}, requestId: req.id } }); return playlist; });
  app.post('/api/v1/playlist/save', async (req, reply) => { const p = playlistSchema.safeParse(req.body); if (!p.success) return fail(reply, req.id, 'INVALID_REQUEST', 'Invalid playlist'); ctx.persistence.savePlaylist(p.data.id, p.data.name, p.data.items); return { ok: true, id: p.data.id }; });
  app.delete('/api/v1/playlist/:id', async (req) => { ctx.persistence.deletePlaylist(String((req.params as { id: string }).id)); return { ok: true }; });
  app.get('/api/v1/events', { preHandler: async (req, reply) => { const value = req.headers.authorization?.replace(/^Bearer\s+/, ''); if (!value || value !== token) return reply.code(401).send(); } }, async (req, reply) => { reply.hijack(); const response = reply.raw; response.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' }); const write = (state: unknown) => response.write(`event: playback.state\ndata: ${JSON.stringify(state)}\n\n`); const listener = (state: unknown) => write(state); ctx.mpv.on('state', listener); write(ctx.mpv.getState()); req.raw.on('close', () => ctx.mpv.off('state', listener)); });
  const stateEmitter = ctx.mpv as unknown as { on?: (event: string, listener: (state: ReturnType<MpvAdapter['getState']>) => void) => void };
  stateEmitter.on?.('state', (state) => { if (!state.path) return; const identity = state.path; ctx.persistence.saveHistory({ id: identity, path: /^https?:\/\//i.test(identity) ? undefined : identity, url: /^https?:\/\//i.test(identity) ? identity : undefined, displayName: state.title || basename(identity), identity, duration: state.duration, position: state.position, completed: state.duration > 0 && (state.duration - state.position <= 120 || state.position / state.duration >= 0.95) }); });
  app.setErrorHandler((error, req, reply) => reply.code(500).send({ error: { code: 'INTERNAL_ERROR', message: 'Unexpected internal error.', details: process.env.CLASSICMP_ENV === 'development' ? String(error) : {}, requestId: req.id } }));
  return { app, token };
}
