import type { BrowserWindow as ElectronBrowserWindow } from 'electron';
import { createRequire } from 'node:module';
import path from 'node:path';
import os from 'node:os';
import { getAppPaths } from './paths.js';
import { Persistence } from '../persistence/database.js';
import { MpvAdapter } from '../playback/mpv/MpvAdapter.js';
import { createApi } from '../api/server.js';
import { startMpris } from './linux/mpris.js';
import { resolveVideoSurface } from './linux/video-surface.js';
const electronRequire = createRequire(__filename); const electron = electronRequire('electron') as typeof import('electron'); const { app, BrowserWindow, dialog, ipcMain, session } = electron;
let windowRef: ElectronBrowserWindow | null = null; let mpv: MpvAdapter; let persistence: Persistence; let api: Awaited<ReturnType<typeof createApi>>; const paths = getAppPaths();
function createWindow(baseUrl: string) { windowRef = new BrowserWindow({ minWidth: 640, minHeight: 360, width: 960, height: 620, webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, allowRunningInsecureContent: false, preload: path.join(app.getAppPath(), 'dist/src/main/preload.js') } }); windowRef.webContents.setWindowOpenHandler(() => ({ action: 'deny' })); windowRef.webContents.on('will-navigate', (event: { preventDefault: () => void }, url: string) => { if (!url.startsWith(baseUrl)) event.preventDefault(); }); void windowRef.loadURL(process.env.CLASSICMP_ENV === 'development' ? 'http://127.0.0.1:5173' : `file://${path.join(app.getAppPath(), 'dist/renderer/index.html')}`); return windowRef; }
async function boot() { if (!app.requestSingleInstanceLock()) return app.quit(); await app.whenReady(); session.defaultSession.webRequest.onHeadersReceived((details, callback) => callback({ responseHeaders: { ...details.responseHeaders, 'Content-Security-Policy': ["default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' http://127.0.0.1:*; object-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'"] } })); persistence = await Persistence.open(paths); mpv = new MpvAdapter(); api = await createApi({ mpv, persistence, version: app.getVersion(), screenshotDirectory: path.join(process.env.XDG_PICTURES_DIR || path.join(os.homedir(), 'Pictures'), 'ClassicMP') }); const address = await api.app.listen({ host: '127.0.0.1', port: 0 }); const port = typeof address === 'string' ? Number(new URL(address).port) : (api.app.server.address() as { port: number }).port; const baseUrl = `http://127.0.0.1:${port}`; ipcMain.handle('bootstrap', () => ({ baseUrl, sessionToken: api.token })); ipcMain.handle('choose-files', async (_event, properties: ('openFile'|'multiSelections')[] = ['openFile']) => (await dialog.showOpenDialog(windowRef!, { properties, filters: [{ name: 'Media Files', extensions: ['mkv','mp4','webm','avi','mov','mp3','flac','wav','m4a'] }, { name: 'All Files', extensions: ['*'] }] })).filePaths); const playerWindow = createWindow(baseUrl); const surface = resolveVideoSurface(playerWindow); console.info(`video surface: ${surface.mode} (${surface.reason})`); try { await mpv.start(path.join(paths.runtime, 'mpv.sock'), 'mpv', surface.mode !== 'managed-wayland', surface.windowId); } catch { /* settings UI remains available without mpv */ } await startMpris(mpv); }
void boot(); app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); }); app.on('before-quit', () => { mpv?.close(); void api?.app.close(); persistence?.close(); });
